siteTitle = "Erdal Mutlu -- Home Page"
siteDescr = "Ph.D. in Computer Science"
siteAuthor = "Erdal Mutlu"

siteTwitterUrl = "https://twitter.com/erdalmutlu"
siteGithubUrl = "https://github.com/erdalmutlu"
siteEmailUrl = "erdalmutlu.su@gmail.com"


googleAnalyticsId = ""

linkPrefix = "/personal_webpage"