siteTitle = "Erdal Mutlu -- Home Page"
siteDescr = "Hi. I'm a recent Ph.D. graduate from Koç University where I worked on Software Reliability.	"
siteAuthor = "Erdal Mutlu"

siteTwitterUrl = "https://twitter.com/erdalmutlu"
siteGithubUrl = "https://github.com/erdalmutlu"
siteEmailUrl = "erdalmutlu.su@gmail.com"


googleAnalyticsId = ""

linkPrefix = ""